# Generated by Django 4.0.6 on 2022-08-01 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BinsByOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_collection', models.DateTimeField()),
                ('bin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questiontwo.bin')),
                ('operation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questiontwo.operation')),
            ],
            options={
                'unique_together': {('bin_id', 'operation_id')},
            },
        ),
    ]
