# Generated by Django 4.0.6 on 2022-08-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questiontwo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='binsbyoperations',
            name='collection_frequency',
            field=models.IntegerField(default=1),
        ),
    ]
